Changes to de_de
DasHomi/preventer pull request #12
Opened 2022-11-25 20:17 UTC by Butterkeks1000

WIP

2022-11-25 20:35 UTC, Butterkeks1000 commented
@DasHomi pls review 🙏

2022-12-02 09:15 UTC, DasHomi requested changes
,

2022-12-02 09:15 UTC, DasHomi commented on src/main/resources/assets/preventer/lang/de_de.json
> -  "text.autoconfig.PreventerConfig.option.preventItemFrameBreaking": "Verhindert das Zerstören von Rahmen",
, is missing

2022-12-02 09:29 UTC, Butterkeks1000 commented on src/main/resources/assets/preventer/lang/de_de.json
> -  "text.autoconfig.PreventerConfig.option.preventItemFrameBreaking": "Verhindert das Zerstören von Rahmen",
Sehr interessant

2022-12-02 09:33 UTC, merged